### ISSUE TITLE
Update with 7.0 stable? And 7.1 sources?

### ISSUE THREAD

**Issue by autonomousapps** [jrodbx/agp-sources#2]
I can do it following the guidance in the readme, but I wanted to check with you first. Do you do it for every alpha/beta/etc release, or could I just grab the latest from 7.0 and 7.1?

**Comment by jrodbx** [comment]
Oops sorry for seeing this sooner.

Yes, i typically bump with every alpha and beta and then once a release comes out, i delete the previous.

**Comment by jrodbx** [comment]
Updated in e77c2ed
