### ISSUE TITLE
[HELP] Can you use these source code, compile an AGP ?

### ISSUE THREAD

**Issue by zhongqingsong** [jrodbx/agp-sources#5]
Hello, I am compiling AGP now. Then I encountered a lot of problems, I searched this place, got AGP source code. So, I want to ask, can you use this source code, compile to get a normal use of AGP? If this is not possible, is there any way to compile an AGP?

**Comment by zhongqingsong** [comment]
I tried this with [Google's compilation guide](https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/README.md).
My environment is **mac 10.13**. I first obtained the code of the **studio-main** branch through repo, which is about 60G in total.
First, repo official source code, and then compile.
Next, I try to follow the above documentation and start compiling. No matter what instruction I run, I get a bunch of errors.
These mistakes, I tried every way, to solve one mistake, there will be a lot of mistakes. I don't think that's right.

**Comment by zhongqingsong** [comment]
After I get the source code, I run gradlew check. Then I get an error, it's about the absence of skia.
First of all, this skia, which is a rendering Android library, has nothing to do with the AGP I need. Second, this skia is really not in the studio-main list. So, I thought maybe I could turn this off. So I went to the WORKSPACE and commented out the skia build. Now skia's error is gone.
However, after check again, new problems appeared again, which were about some missing bzl, and this problem was more special. I feel that these problems cannot be solved manually.

It's possible that I did it the wrong way, or the compilation process, but the Google documentation doesn't say how to do it. Therefore, I hope that some friends who know can give me some advice or help. I'd appreciate even a link to a web page.

**Comment by jrodbx** [comment]
> can you use this source code, compile to get a normal use of AGP?

probably not.  the scripts in this repo just pull the binary artifacts down and unzips them mainly for the Kotlin sources to peek and do quick diffs for troubleshooting potential issues when migrating between versions.

> I tried this with [Google's compilation guide](https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/README.md).

It looks like what you're trying with the Google compilation guide is on the right track.  Perhaps filing an issue on [Google's issue tracker](https://issuetracker.google.com/) asking how to compile AGP from source will help you resolve this issue?

I've tried compiling AGP in the past and hit similar pitfalls that ultimately led me to pivot to another approach, so I'm not much help here.  Sorry.
